export const REQUEST_APPLICANTS = 'REQUEST_APPLICANTS';
export const RECEIVE_APPLICANTS = 'RECEIVE_APPLICANTS';
export const ACCEPT_APPLICANT = 'ACCEPT_APPLICANT';
export const RECEIVE_APPLICANTS_FAIL = 'RECEIVE_APPLICANTS_FAIL';